replicaCount: 1

image: morozovav82/auth:2.0

service:
  type: NodePort
  port: 9010

appBasePath: '/auth/'
usersUrl: 'http://users-users-chart.morozovav.svc.cluster.local:9000'

redis:
  host: redis-master.morozovav.svc.cluster.local
  port: 6379

ingress:
  enabled: true
  hosts:
    - host: arch.homework
      paths: ["/auth"]
      
metrics:
  serviceMonitor:
    enabled: true