apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-chart.fullname" . }}
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: logging_level_ru_morozov
              value: debug
            - name: app_basePath
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: BASE_APP_URL
            - name: users_url
              valueFrom:
                configMapKeyRef:
                  name: auth-config
                  key: USERS_URL

